name: Render Mermaid Diagrams

on:
  push:
    paths:
      - 'diagrams/*.mmd'

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Mermaid CLI
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Generate diagram image
        run: |
          mkdir -p diagrams/output
          mmdc -i diagrams/Jerod2DEngine.mmd -o diagrams/output/Jerod2DEngine.png

      - name: Commit rendered image
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add diagrams/output/flowchart.png
          git commit -m "Auto-update Mermaid diagram"
          git push
